VERSION 0.6

emacs:
    FROM silex/emacs:master
    WORKDIR /root/.config/emacs

deps:
    FROM +emacs
    RUN apt update
    RUN DEBIAN_FRONTEND=noninteractive apt install git --yes

test:
    FROM +deps
    COPY +emacs-files/emacs/early-init.el /root/.config/emacs/
    COPY +emacs-files/emacs/init.el /root/.config/emacs/
    COPY +emacs-files/emacs/config.org /root/.config/emacs/
    IF [ -f +emacs-files/emacs/custom.el ]
        COPY +emacs-files/emacs/custom.el /root/.config/emacs/
    END
    COPY test.el .
    RUN emacs --batch -l test.el

# https://github.com/earthly/earthly/issues/1221#issuecomment-925390672
emacs-files:
    LOCALLY
    SAVE ARTIFACT ../emacs emacs
