[settings]
experimental = true

[tasks.update]
description = "Update flake inputs"
run = "nix flake update"

[tasks.build]
description = "Build emacs-git-pgtk from emacs-overlay"
run = "nix build --print-build-logs"
