* Unbind the =suspend-frame= vs ~suspend-frame~ command.

#+begin_src emacs-lisp :results none
(global-unset-key (kbd "C-x C-z"))
#+end_src

#+begin_src emacs-lisp :results none
(when (string-equal system-type "gnu/linux")
  (add-to-list 'load-path "~/.guix-profile/share/emacs/site-lisp")
  (guix-emacs-autoload-packages))

(when (or (string-equal system-type "berkley-unix") (string-equal system-type "gnu/linux"))
  (use-package exwm)
  (require 'exwm)
  (require 'exwm-config)
  (require 'exwm-randr)
  (setq exwm-randr-workspace-output-plist
        '(0 "Virtual-1"))
  (add-hook 'exwm-randr-screen-change-hook
            (lambda
              ()
              (start-process-shell-command
               "xrandr" nil "xrandr -s 2560x1800 --output Virtual-1 --auto")))
  (exwm-randr-enable)
  (exwm-config-default)
  (setq exwm-input-global-keys
        `(
          ;; 's-r': Reset (to line-mode).
          ;; ([?\s-r]
          ;;  . exwm-reset)
          ;; 's-&': Launch application.
          ([?\s-&]
           .
           (lambda
             (command)
             (interactive
              (list
               (read-shell-command "$ ")))
             (start-process-shell-command command nil command))))))

(use-package
  emacs
  :elpaca nil
  :config (recentf-mode t)
  (setq recentf-max-menu-items 10000)
  (setq recentf-max-saved-items 10000)
  (show-paren-mode 1)
  (setq show-paren-style 'expression)
  (set-face-attribute 'show-paren-match-expression nil :background "blue")
  (menu-bar-mode -1)
  (toggle-scroll-bar -1)
  (tool-bar-mode -1)
  (ido-mode -1)
  (global-auto-revert-mode 1)
  (setq make-backup-files nil)
  (setq markdown-command "pandoc")
  (setq-default indent-tabs-mode nil)
  (setq auto-save-no-message t)
  (setq ediff-window-setup-function 'ediff-setup-windows-plain)
  (setq ediff-split-window-function 'split-window-horizontally)
  (electric-pair-mode t)
  (display-time-mode 1)
  (setq display-time-default-load-average nil)
  (setq display-time-format "%F %H:%M - %a")
  (if (or (string-equal system-type "berkley-unix") (string-equal system-type "gnu/linux"))
      (setq browse-url-browser-function 'browse-url-generic
            browse-url-generic-program "nyxt")
    (setq browse-url-browser-function 'browse-url-default-macosx-browser))
  (setq backup-directory-alist `(("." . ,(concat user-emacs-directory "backups"))))
  (setq auto-save-file-name-transforms `((".*" ,(concat user-emacs-directory "auto-saves/") t)))
  (setq lock-file-name-transforms `((".*" ,(concat user-emacs-directory "locks/") t)))
  ;; (setq split-window-preferred-function 'split-window-horizontally)
  ;; (add-to-list 'default-frame-alist '(font . "Menlo-10"))
  (setq delete-by-moving-to-trash t)
  (setq initial-major-mode #'org-mode)
  (setq initial-scratch-message "* test\n#+begin_src emacs-lisp\n#+end_src")
  (setq window-combination-resize t)
  (setq use-short-answers t)
  (delete-selection-mode 1)
  (setq-default mode-line-buffer-identification
                (list
                 'buffer-file-name
                 (propertized-buffer-identification "%12f")
                 (propertized-buffer-identification "%12b")))
  ;; this allows for Copying or Renaming across dired buffers
  (setq dired-dwim-target t)
  (setq native-comp-async-report-warnings-errors 'silent)
  :bind (;; Better than default - from /u/zck
         ("M-c" . capitalize-dwim)
         ("M-l" . downcase-dwim)
         ("M-u" . upcase-dwim)
         ("s-a" . mark-whole-buffer)
         ("s-u" . revert-buffer))
  :hook ((prog-mode . hl-line-mode)
         (text-mode . hl-line-mode)
         (prog-mode . display-line-numbers-mode)
         (text-mode . display-line-numbers-mode)))

(use-package
  affe
  :after orderless
  :config
  (setq affe-count 10000)
  (setq affe-regexp-function #'orderless-pattern-compiler
        affe-highlight-function #'orderless--highlight
        affe-find-command "rg --color=never --files --hidden -g !.git/*"
        affe-grep-command "rg --null --color=never --max-columns=1000 --no-heading --line-number -v ^$ . --hidden -g !.git/*")
  :bind (("M-s af" . affe-find)
         ("M-s ag" . affe-grep)))

;; Example configuration for Consult
(use-package consult
  :bind (("C-c m" . consult-man)
         ("C-c i" . consult-info)
         ([remap Info-search] . consult-info)
         ("C-x b" . consult-buffer)                ;; orig. switch-to-buffer
         ("C-x r b" . consult-bookmark)            ;; orig. bookmark-jump
         ("C-x p b" . consult-project-buffer)      ;; orig. project-switch-to-buffer
         ;; Other custom bindings
         ("M-y" . consult-yank-pop)                ;; orig. yank-pop
         ("M-g e" . consult-compile-error)
         ("M-g f" . consult-flymake)               ;; Alternative: consult-flycheck
         ("M-g g" . consult-goto-line)             ;; orig. goto-line
         ("M-g M-g" . consult-goto-line)           ;; orig. goto-line
         ("M-g o" . consult-outline)               ;; Alternative: consult-org-heading
         ("s-f" . consult-line))
  :hook (completion-list-mode . consult-preview-at-point-mode)
  :init
  (setq register-preview-delay 0.5
        register-preview-function #'consult-register-format)
  (advice-add #'register-preview :override #'consult-register-window)
  (setq xref-show-xrefs-function #'consult-xref
        xref-show-definitions-function #'consult-xref)
  :config
  (consult-customize
   consult-theme :preview-key '(:debounce 0.2 any)
   consult-ripgrep consult-git-grep consult-grep
   consult-bookmark consult-recent-file consult-xref
   consult--source-bookmark consult--source-file-register
   consult--source-recent-file consult--source-project-recent-file
   ;; :preview-key "M-."
   :preview-key '(:debounce 0.4 any))
  (setq consult-narrow-key "<") ;; "C-+"
)

(use-package
  marginalia
  :config (marginalia-mode)
  (setq marginalia-annotators '(marginalia-annotators-heavy marginalia-annotators-light nil)))

(use-package
  embark
  :bind ("M-a" . embark-act))

(use-package
  embark-consult
  :after (embark consult)
  :demand t
  :hook (embark-collect-mode . embark-consult-preview-minor-mode))

(use-package orderless
  :custom
  (completion-styles '(orderless basic))
  (completion-category-overrides '((file (styles basic partial-completion)))))

(with-eval-after-load 'eglot
  (setq completion-category-defaults nil))

(use-package vertico
  :init
  (vertico-mode))

;; Persist history over Emacs restarts. Vertico sorts by history position.
(use-package savehist
  :straight t
  :init
  (savehist-mode))

(use-package corfu
  :custom
  (corfu-auto t)        ;; Enable auto completion
  (corfu-separator ?\s) ;; Orderless field separator
  (corfu-auto-delay 0.0)
  :init
  (global-corfu-mode))

(unless (display-graphic-p)
  (use-package corfu-terminal
    :init
    (corfu-terminal-mode +1)))

(use-package
  default-text-scale
  :config
  :hook (after-init . default-text-scale-mode)
  :bind (("s-=" . default-text-scale-increase)
         ("s--" . default-text-scale-decrease)
         ("C-x C-0" . default-text-scale-reset)))

(use-package
  wgrep
  :config (setq wgrep-auto-save-buffer t)
  (setq wgrep-enable-key "r"))

(use-package
  rg
  :config (rg-enable-default-bindings)
  (rg-enable-menu))

(defun johnny5-split-window-horizontally ()
  (interactive)
  (split-window-horizontally)
  (balance-windows))

(defun johnny5-delete-window-evenly ()
  (interactive)
  (delete-window)
  (balance-windows))

(defun johnny5-split-window-below ()
  (interactive)
  (split-window-below)
  (balance-windows))

(global-set-key "\C-x3" 'johnny5-split-window-horizontally)
(global-set-key "\C-x2" 'johnny5-split-window-below)
(global-set-key "\C-x0" 'johnny5-delete-window-evenly)

;;; It is the opposite of fill-paragraph
(defun unfill-paragraph ()
  "Takes a multi-line paragraph and makes it into a single line of text."
  (interactive)
  (let ((fill-column (point-max)))
    (fill-paragraph nil)))

(define-key global-map "\M-Q" 'unfill-paragraph)

;; (use-package exec-path-from-shell
;;   :straight t
;;   :config
;;   (dolist (var '("SSH_AUTH_SOCK" "SSH_AGENT_PID" "GPG_AGENT_INFO" "LANG" "LC_CTYPE" "NIX_SSL_CERT_FILE" "NIX_PATH"))
;;   (add-to-list 'exec-path-from-shell-variables var))
;;   (when (memq window-system '(mac ns x))
;;     (exec-path-from-shell-initialize)))

;; try to setup spell-fu on macOS so we can remove these guards.
(when (string-equal system-type "gnu/linux")
  (use-package
    spell-fu))
(when (string-equal system-type "gnu/linux")
  (add-hook 'org-mode-hook (lambda ()
                             (setq spell-fu-faces-exclude '(org-block-begin-line org-block-end-line
                                                                                 org-code org-date
                                                                                 org-drawer
                                                                                 org-document-info-keyword
                                                                                 org-ellipsis org-link
                                                                                 org-meta-line
                                                                                 org-properties
                                                                                 org-properties-value
                                                                                 org-special-keyword
                                                                                 org-src org-tag
                                                                                 org-verbatim))
                             (spell-fu-mode))))
(when (string-equal system-type "gnu/linux")
  (add-hook 'emacs-lisp-mode-hook (lambda () (spell-fu-mode))))

(use-package
  magit
  :init (add-to-list 'project-switch-commands '(magit-project-status "Magit" "m"))
  :bind (("C-x g" . magit-project-status)))

(setq johnny5-package-list
      '(deadgrep define-word
             ;; docker
             elfeed flycheck-yamllint git-link git-timemachine
             htmlize ipcalc jeison json-mode kubel markdown-mode ob-elixir orgit
             org-chef org-contrib org-ql ox-jira pdf-tools powerthesaurus ;; ruby-mode
             ;; speed-type
             string-inflection
             ))

(dolist (package johnny5-package-list)
  (eval `(use-package ,package) t))

(use-package
  git-identity
  :after magit
  :config (git-identity-magit-mode 1)
  (define-key magit-status-mode-map (kbd "I") 'git-identity-info)
  :custom (git-identity-verify t))

;; (org-narrow-to-subtree) C-x n s
;; (widen) C-x n w
(use-package
  org
  :elpaca nil
  :bind (("C-c c" . 'org-capture)
         ("C-c a" . 'org-agenda))
  :config (setq org-confirm-babel-evaluate nil)
  (setq org-src-fontify-natively t)
  (setq org-src-preserve-indentation t)
  (setq org-edit-src-content-indentation t)
  (setq org-log-into-drawer t)
  ;; NOT-RETAINED - will not continue in the application process
  (setq org-todo-keywords '((sequence "TODO(t!)" "IN-PROGRESS(i!)" "WAIT(w!)" "APPLIED(a!)" "|" "DONE(d@)"
                                      "CANCELED(@)" "WITHDRAWN(@)" "FILLED" "HIRED" "NOT-RETAINED(n@)")))
  (setq org-refile-targets '((org-agenda-files :maxlevel . 2)))
  (setq org-agenda-files '("~/dev/org" "~/dev/notes"))
  ;; (setq org-agenda-include-inactive-timestamps 't)
  (setq org-log-refile 'note)
  (setq org-refile-use-outline-path 'file)
  (setq org-outline-path-complete-in-steps nil)
  (setq org-refile-allow-creating-parent-nodes 'confirm)
  (setq org-startup-indented t)
  (add-hook 'auto-save-hook 'org-save-all-org-buffers)
  (progn
    (defun imalison:org-inline-css-hook (exporter)
      "Insert custom inline css to automatically set the
  background of code to whatever theme I'm using's background"
      (when (eq exporter 'html)
        (let* ((my-pre-bg (face-background 'default))
               (my-pre-fg (face-foreground 'default)))
          (setq org-html-head-extra (concat org-html-head-extra (format
                                                                 "<style type=\"text/css\">\n pre.src {background-color: %s; color: %s;}</style>\n"
                                                                 my-pre-bg my-pre-fg))))))
    (add-hook 'org-export-before-processing-hook 'imalison:org-inline-css-hook))
  :mode (("\\.org$" . org-mode)))

(setq org-capture-templates '(("t" "Todo" entry (file "~/dev/org/inbox.org")
                               "* TODO %? [/]\n:PROPERTIES:\n:Created: %U\nEND:\n %i\n %a")
                              ("c" "Cookbook" entry (file "~/dev/org/cookbook.org")
                               "%(org-chef-get-recipe-from-url)"
                               :empty-lines 1)
                              ("m" "Manual Cookbook" entry (file "~/dev/org/cookbook.org")
                               "* %^{Recipe title: }\n  :PROPERTIES:\n  :source-url:\n  :servings:\n  :prep-time:\n  :cook-time:\n  :ready-in:\n  :END:\n** Ingredients\n   %?\n** Directions\n\n")))

(require 'ox-md nil t)
(org-babel-do-load-languages 'org-babel-load-languages '((awk . t)
                                                         (emacs-lisp . t)
                                                         (eshell . t)
                                                         ;; (elixir . t)
                                                         (perl . t)
                                                         (python . t)
                                                         (sed . t)
                                                         (shell . t)
                                                         (sql . t)
                                                         (ruby . t)))

(use-package python-mode
  :init
  (setq python-indent-offset 2))
;; just add :async to any org babel src blocks!
(use-package
  ob-async
  :config (require 'ob-async))

(use-package
  denote
  :config
  (setq denote-directory "~/dev/notes"))

;; (use-package org-download
;;   :straight t
;;   :after org
;;   :defer nil
;;   :custom
;;   (org-download-method 'directory)
;;   (org-download-image-dir "images")
;;   (org-download-heading-lvl nil)
;;   (org-download-timestamp "%Y%m%d-%H%M%S_")
;;   (org-image-actual-width 300)
;;   (org-download-screenshot-method "/usr/local/bin/pngpaste %s")
;;   :bind
;;   ("C-M-y" . org-download-screenshot)
;;   :config
;;   (require 'org-download))

(setq treesit-extra-load-path '("/Users/dj_goku/dev/github/casouri/tree-sitter-module/dist"))

(use-package heex-ts-mode)

(use-package elixir-ts-mode
   :config (global-subword-mode t))

;; M-. xref-find-definitions
;; M-? xref-find-references
(use-package eglot
  :config
  (dolist (mode '(elixir-ts-mode heex-ts-mode))
    (add-to-list 'eglot-server-programs `(,mode . ("/Users/dj_goku/dev/github/elixir-lsp/elixir-ls/release/language_server.sh"))))
  (add-to-list 'eglot-server-programs
               '((python-mode python-ts-mode) "pyright-langserver" "--stdio"))
  :hook ((elixir-ts-mode . eglot-ensure)
         (heex-ts-mode . eglot-ensure)
         (elixir-ts-mode . eglot-ensure)
         (python-mode . eglot-ensure)
         (python-ts-mode . eglot-ensure)))

;; (use-package
;;   eglot-grammarly
;;   :straight (:host github
;;                    :repo "emacs-grammarly/eglot-grammarly")
;;   :hook ((text-mode markdown-mode org-mode). (lambda ()
;;                                                (require 'eglot-grammarly)
;;                                                (eglot-ensure))))

;; (setq
;;  eglot-server-programs
;;  '((elixir-mode
;;     .
;;     ("~/dev/github/elixir-lsp/elixir-ls/release/language_server.sh"))
;;     ((text-mode latex-mode org-mode markdown-mode) eglot-grammarly-server
;;     "node"
;;     "~/node_modules/\@emacs-grammarly/grammarly-languageserver/bin/server.js"
;;     "--stdio"))
;;    ))

;; (use-package
;;  eglot-ltex
;;  :straight (:host github :repo "emacs-languagetool/eglot-ltex")
;;  :hook ;; (text-mode . (lambda () (require 'eglot-ltex) (call-interactively #'eglot)))
;;  ;; (org-mode . (lambda ()
;;  ;;               (require 'eglot-ltex
;;  ;;                        (call-interactively #'eglot))))
;;  (markdown-mode
;;   .
;;   (lambda ()
;;     (require 'eglot-ltex (call-interactively #'eglot))))
;;  :init
;;  (setq
;;   eglot-languagetool-server-path
;;   "/home/johnny/lsp/ltex-ls-15.2.1-alpha.1.nightly.2022-11-04"))

;; TODO
;; (add-to-list 'eglot-server-programs
;;              '((web-mode :language-id "html")
;;                .
;;                ("/home/johnny/node_modules/@tailwindcss/language-server/bin/tailwindcss-language-server")))
;; npm install -g @tailwindcss/language-server

(use-package
  which-key
  :config (which-key-mode))

(use-package
  switch-window
  :bind (("C-x o" . switch-window))
  :config (setq switch-window-shortcut-style 'qwerty)
  (setq switch-window-minibuffer-shortcut ?z))

;; (use-package
;;   tramp)

;; ;; (defun crontab-e ()
;; ;;     "Run `crontab -e' in a emacs buffer."
;; ;;     (interactive)
;; ;;     (with-editor-async-shell-command "crontab -e"))

(use-package
  multiple-cursors
  :config (setq mc/always-run-for-all 1)
  (define-key mc/keymap (kbd "<return>") nil)
  :bind (("s-d" . mc/mark-next-like-this)
         ("s-D" . mc/mark-all-dwim)
         ("M-s-d" . mc/edit-beginnings-of-lines)))

(use-package avy
  :bind (("M-j" . avy-goto-char-timer)))

(use-package
  vterm
  :config (setq vterm-buffer-name-string "vterm %s")
  (setq vterm-kill-buffer-on-exit nil)
  (setq vterm-max-scrollback 100000)
  (setq vterm-use-vterm-prompt-detection-method t)
  (add-to-list 'vterm-eval-cmds '("update-pwd" (lambda (path)
                                                 (setq default-directory path)))))

(defun screenshot-svg ()
  "Save a screenshot of the current frame as an SVG image.
  Saves to a temp file and puts the filename in the kill ring."
  (interactive)
  (let* ((filename (make-temp-file "Emacs" nil ".png"))
         (data (x-export-frames nil 'png)))
    (with-temp-file filename
      (insert data))
    (kill-new filename)
    (message filename)))

(use-package
  elisp-demos
  :init
  (advice-add 'describe-function-1 :after #'elisp-demos-advice-describe-function-1))

(use-package
  envrc
  :config (envrc-global-mode))

(when (file-exists-p "~/.config/emacs/custom.el")
  (setq custom-file "~/.config/emacs/custom.el")
  (load custom-file))
#+end_src
