name: Earthly
on:
  push:
    paths:
      - 'emacs/**.el'
      - 'emacs/**.org'
      - '.github/**.yml'
jobs:
  tests:
    name: Testing Emacs
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: "latest"
      - uses: actions/checkout@v2
      - name: Docker login
        run: docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password "${{ secrets.DOCKERHUB_PASSWORD }}"
      - name: run earthly for testing emacs
        run: earthly ./earthly+test
