name: Earthly

on:
  push:
    paths:
      - 'emacs/**.el'
      - 'emacs/**.org'
jobs:
  tests:
    name: Testing Emacs
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: "latest"
      - uses: actions/checkout@v2
      - name: run earthly for testing emacs
        run: earthly ./earthly+test
